[2023-01-18T22:34:00.442+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T22:33:23.230011+00:00 [queued]>
[2023-01-18T22:34:00.451+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T22:33:23.230011+00:00 [queued]>
[2023-01-18T22:34:00.451+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T22:34:00.451+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 7
[2023-01-18T22:34:00.451+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T22:34:00.478+0000] {taskinstance.py:1304} INFO - Executing <Task(ProduceToTopicOperator): producer> on 2023-01-18 22:33:23.230011+00:00
[2023-01-18T22:34:00.484+0000] {standard_task_runner.py:55} INFO - Started process 437 to run task
[2023-01-18T22:34:00.488+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-18T22:33:23.230011+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmp_96fex_h']
[2023-01-18T22:34:00.489+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask producer
[2023-01-18T22:34:00.545+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-18T22:33:23.230011+00:00 [running]> on host 8a5dd0629494
[2023-01-18T22:34:00.601+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T22:33:23.230011+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T22:33:23.230011+00:00
[2023-01-18T22:34:00.604+0000] {producer.py:55} INFO - Producer <cimpl.Producer object at 0x7f72d074b940>
[2023-01-18T22:34:00.606+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: connecting to 172.22.0.7:9092 [('172.22.0.7', 9092) IPv4]
[2023-01-18T22:34:00.606+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T22:34:02.608+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_provider_kafka/operators/produce_to_topic.py", line 114, in execute
    for k, v in producer_callable():
  File "/opt/airflow/dags/producer_dag.py", line 12, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T22:34:02.615+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230118T223323, start_date=20230118T223400, end_date=20230118T223402
[2023-01-18T22:34:02.626+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task producer (NoBrokersAvailable; 437)
[2023-01-18T22:34:02.671+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T22:34:02.686+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
