[2023-01-27T16:59:58.035+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Status_info_mongodb manual__2023-01-27T16:26:14.836684+00:00 [queued]>
[2023-01-27T16:59:58.049+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Status_info_mongodb manual__2023-01-27T16:26:14.836684+00:00 [queued]>
[2023-01-27T16:59:58.050+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T16:59:58.050+0000] {taskinstance.py:1284} INFO - Starting attempt 13 of 18
[2023-01-27T16:59:58.050+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T16:59:58.065+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Status_info_mongodb> on 2023-01-27 16:26:14.836684+00:00
[2023-01-27T16:59:58.069+0000] {standard_task_runner.py:55} INFO - Started process 3053 to run task
[2023-01-27T16:59:58.072+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Status_info_mongodb', 'manual__2023-01-27T16:26:14.836684+00:00', '--job-id', '1111', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpk3ksiq_9']
[2023-01-27T16:59:58.072+0000] {standard_task_runner.py:83} INFO - Job 1111: Subtask Status_info_mongodb
[2023-01-27T16:59:58.121+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Status_info_mongodb manual__2023-01-27T16:26:14.836684+00:00 [running]> on host 502660defd2e
[2023-01-27T16:59:58.192+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Status_info_mongodb
AIRFLOW_CTX_EXECUTION_DATE=2023-01-27T16:26:14.836684+00:00
AIRFLOW_CTX_TRY_NUMBER=13
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-27T16:26:14.836684+00:00
[2023-01-27T17:00:08.211+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-01-27T17:00:08.213+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 3053. PIDs of all processes in the group: [3053]
[2023-01-27T17:00:08.213+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 3053
[2023-01-27T17:00:08.214+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-27T17:00:08.214+0000] {producer_dag.py:70} ERROR - Error al conectar a mongoDB: Task received SIGTERM signal
[2023-01-27T17:00:08.214+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-27T17:00:08.224+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Streaming_pipeline_meli, task_id=Status_info_mongodb, execution_date=20230127T162614, start_date=20230127T165958, end_date=20230127T170008
[2023-01-27T17:00:08.267+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3053, status='terminated', exitcode=0, started='16:59:57') (3053) terminated with exit code 0
