[2023-01-20T00:02:52.153+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.submit_data_to_kafka manual__2023-01-19T22:08:17.592063+00:00 [queued]>
[2023-01-20T00:02:52.163+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.submit_data_to_kafka manual__2023-01-19T22:08:17.592063+00:00 [queued]>
[2023-01-20T00:02:52.163+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T00:02:52.164+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 7
[2023-01-20T00:02:52.164+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T00:02:52.178+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): submit_data_to_kafka> on 2023-01-19 22:08:17.592063+00:00
[2023-01-20T00:02:52.181+0000] {standard_task_runner.py:55} INFO - Started process 771 to run task
[2023-01-20T00:02:52.184+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'submit_data_to_kafka', 'manual__2023-01-19T22:08:17.592063+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpunerhlmc']
[2023-01-20T00:02:52.185+0000] {standard_task_runner.py:83} INFO - Job 233: Subtask submit_data_to_kafka
[2023-01-20T00:02:52.236+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.submit_data_to_kafka manual__2023-01-19T22:08:17.592063+00:00 [running]> on host ebf057e34173
[2023-01-20T00:02:52.303+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=submit_data_to_kafka
AIRFLOW_CTX_EXECUTION_DATE=2023-01-19T22:08:17.592063+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-19T22:08:17.592063+00:00
[2023-01-20T00:02:52.305+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2023-01-20T00:02:52.308+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-20T00:02:52.308+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Connection complete.
[2023-01-20T00:02:52.420+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2023-01-20T00:02:52.420+0000] {conn.py:1269} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2023-01-20T00:02:52.422+0000] {producer_dag.py:18} INFO - Conexion exitosa a kafka: <kafka.producer.kafka.KafkaProducer object at 0x7fc0cd5b3d50>
[2023-01-20T00:02:53.270+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:53.271+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:53.271+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:53.272+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:53.425+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:53.425+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:53.425+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:53.425+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:53.577+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:53.577+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:53.577+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:53.577+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:53.879+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:53.880+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:53.880+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:53.880+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:54.333+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:54.333+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:54.334+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:54.334+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:55.092+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:55.093+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:55.094+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:55.095+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:56.356+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:56.357+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:56.357+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:56.357+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:57.562+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:57.563+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:57.563+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:57.563+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:58.673+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:58.674+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:58.675+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:58.675+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:02:59.785+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:02:59.786+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:02:59.786+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:02:59.786+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:00.946+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:00.947+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:00.947+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:00.948+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:02.160+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:02.162+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:02.162+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:02.163+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:03.307+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:03.308+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:03.308+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:03.308+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:04.464+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:04.464+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:04.464+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:04.464+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:05.424+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:05.425+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:05.426+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:05.426+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:06.383+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:06.383+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:06.383+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:06.384+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:07.548+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:07.550+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:07.550+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:07.551+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:08.709+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:08.709+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:08.709+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:08.711+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:09.615+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:09.615+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:09.615+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:09.616+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:10.829+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:10.830+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:10.831+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:10.832+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:12.090+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:12.090+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:12.090+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:12.091+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:13.351+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:13.352+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:13.353+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:13.353+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:14.615+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:14.616+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:14.616+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:14.616+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:15.772+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:15.773+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:15.773+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:15.773+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:16.884+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:16.885+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:16.885+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:16.886+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:18.109+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:18.110+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:18.110+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:18.110+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:19.121+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:19.122+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:19.123+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:19.123+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:20.380+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:20.380+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:20.381+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:20.381+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:21.341+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:21.342+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:21.342+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:21.342+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:22.250+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:22.251+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:22.251+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:22.251+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:23.513+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:23.514+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:23.515+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:23.515+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:24.624+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:24.624+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:24.624+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:24.625+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:25.686+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:25.687+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:25.688+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:25.688+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:26.647+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:26.648+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:26.649+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:26.649+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:27.906+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:27.907+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:27.907+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:27.907+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:28.815+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:28.815+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:28.816+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:28.816+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:29.927+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:29.928+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:29.929+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:29.929+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:31.137+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:31.137+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:31.137+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:31.137+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:32.197+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:32.198+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:32.198+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:32.198+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:33.404+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:33.405+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:33.405+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:33.405+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:34.315+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:34.316+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:34.316+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:34.317+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:35.324+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:35.324+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:35.324+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:35.325+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:36.435+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:36.436+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:36.437+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:36.437+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:37.448+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:37.449+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:37.450+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:37.450+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:38.562+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:38.563+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:38.564+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:38.564+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:39.476+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:39.476+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:39.476+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:39.476+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:40.533+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:40.533+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:40.533+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:40.534+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:41.594+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:41.595+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:41.596+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:41.597+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:42.504+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:42.504+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:42.504+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:42.505+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:43.763+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:43.764+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:43.764+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:43.764+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:44.872+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:44.873+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:44.873+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:44.873+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:46.030+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:46.030+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:46.031+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:46.031+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:46.936+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:46.937+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:46.937+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:46.937+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:47.893+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:47.894+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:47.894+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:47.894+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:48.903+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:48.903+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:48.903+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:48.904+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:50.167+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:50.168+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:50.168+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:50.169+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:51.228+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:51.228+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:51.228+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:51.229+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:52.434+0000] {conn.py:381} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: connecting to tomi-H310:9092 [('127.0.1.1', 9092) IPv4]
[2023-01-20T00:03:52.434+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]> returned error 111. Disconnecting.
[2023-01-20T00:03:52.435+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=tomi-H310:9092 <connecting> [IPv4 ('127.0.1.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-20T00:03:52.435+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2023-01-20T00:03:53.217+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 48, in runKafkaProducer
    producer.send('myTopic', data)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 576, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 703, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2023-01-20T00:03:53.264+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=submit_data_to_kafka, execution_date=20230119T220817, start_date=20230120T000252, end_date=20230120T000353
[2023-01-20T00:03:53.277+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 233 for task submit_data_to_kafka (KafkaTimeoutError: Failed to update metadata after 60.0 secs.; 771)
[2023-01-20T00:03:53.305+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-20T00:03:53.325+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
