[2023-01-18T21:10:20.475+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T21:10:20.483+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T21:10:20.483+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:10:20.484+0000] {taskinstance.py:1284} INFO - Starting attempt 42 of 46
[2023-01-18T21:10:20.484+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:10:20.497+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-17 19:52:55.119227+00:00
[2023-01-18T21:10:20.502+0000] {standard_task_runner.py:55} INFO - Started process 3985 to run task
[2023-01-18T21:10:20.504+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-17T19:52:55.119227+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpj0fwd9dw']
[2023-01-18T21:10:20.504+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask producer
[2023-01-18T21:10:20.559+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [running]> on host 7a3ca62d008e
[2023-01-18T21:10:20.616+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T19:52:55.119227+00:00
AIRFLOW_CTX_TRY_NUMBER=42
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T19:52:55.119227+00:00
[2023-01-18T21:10:20.618+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.20.0.3:9092 <connecting> [IPv4 ('172.20.0.3', 9092)]>: connecting to 172.20.0.3:9092 [('172.20.0.3', 9092) IPv4]
[2023-01-18T21:10:20.618+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T21:10:22.620+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 10, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T21:10:22.630+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230117T195255, start_date=20230118T211020, end_date=20230118T211022
[2023-01-18T21:10:22.658+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task producer (NoBrokersAvailable; 3985)
[2023-01-18T21:10:22.680+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T21:10:22.698+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
