[2023-01-18T22:23:32.463+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T22:23:32.470+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T22:23:32.470+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T22:23:32.470+0000] {taskinstance.py:1284} INFO - Starting attempt 21 of 26
[2023-01-18T22:23:32.470+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T22:23:32.481+0000] {taskinstance.py:1304} INFO - Executing <Task(ProduceToTopicOperator): producer> on 2023-01-18 21:35:11.718856+00:00
[2023-01-18T22:23:32.486+0000] {standard_task_runner.py:55} INFO - Started process 4318 to run task
[2023-01-18T22:23:32.488+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-18T21:35:11.718856+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpzhqbrxpk']
[2023-01-18T22:23:32.488+0000] {standard_task_runner.py:83} INFO - Job 89: Subtask producer
[2023-01-18T22:23:32.535+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [running]> on host f2df97c6ee42
[2023-01-18T22:23:32.589+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T21:35:11.718856+00:00
AIRFLOW_CTX_TRY_NUMBER=21
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T21:35:11.718856+00:00
[2023-01-18T22:23:32.592+0000] {producer.py:55} INFO - Producer <cimpl.Producer object at 0x7f5538855470>
[2023-01-18T22:24:28.275+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-01-18T22:24:28.277+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4318. PIDs of all processes in the group: [4318]
[2023-01-18T22:24:28.277+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4318
[2023-01-18T22:25:28.294+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=4318, name='airflow task ru', status='sleeping', started='22:23:31') did not respond to SIGTERM. Trying SIGKILL
[2023-01-18T22:25:28.299+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 4318
[2023-01-18T22:25:28.327+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4318, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='22:23:31') (4318) terminated with exit code Negsignal.SIGKILL
[2023-01-18T22:25:28.328+0000] {standard_task_runner.py:170} ERROR - Job 89 was killed before it finished (likely due to running out of memory)
