[2023-01-18T21:43:00.389+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T21:43:00.399+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T21:43:00.399+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:43:00.399+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 10
[2023-01-18T21:43:00.399+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:43:00.421+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-18 21:35:11.718856+00:00
[2023-01-18T21:43:00.426+0000] {standard_task_runner.py:55} INFO - Started process 1819 to run task
[2023-01-18T21:43:00.430+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-18T21:35:11.718856+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpaupc5fm5']
[2023-01-18T21:43:00.431+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask producer
[2023-01-18T21:43:00.491+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [running]> on host f2df97c6ee42
[2023-01-18T21:43:00.562+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T21:35:11.718856+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T21:35:11.718856+00:00
[2023-01-18T21:43:00.564+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.24.0.3:2181 <connecting> [IPv4 ('172.24.0.3', 2181)]>: connecting to 172.24.0.3:2181 [('172.24.0.3', 2181) IPv4]
[2023-01-18T21:43:00.564+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T21:43:02.567+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 12, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T21:43:02.578+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230118T213511, start_date=20230118T214300, end_date=20230118T214302
[2023-01-18T21:43:02.588+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task producer (NoBrokersAvailable; 1819)
[2023-01-18T21:43:02.617+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T21:43:02.645+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
